// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfZpwJMiHp8Ar7mVKd3FgCXUA_s-QzqHw',
    appId: '1:262291939280:web:9a117f4b0b1d35db7923d5',
    messagingSenderId: '262291939280',
    projectId: 'fitfuse-5edc7',
    authDomain: 'fitfuse-5edc7.firebaseapp.com',
    storageBucket: 'fitfuse-5edc7.firebasestorage.app',
    measurementId: 'G-PY21MNLLWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8KQUTkNLLHCp9TqY3csXlUqBEd5GSALY',
    appId: '1:262291939280:android:c5d905acff2096d17923d5',
    messagingSenderId: '262291939280',
    projectId: 'fitfuse-5edc7',
    storageBucket: 'fitfuse-5edc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsoFTCMtGbtlrABbl9xrh-TkUw2oBd5G8',
    appId: '1:262291939280:ios:6773e8b1375469d27923d5',
    messagingSenderId: '262291939280',
    projectId: 'fitfuse-5edc7',
    storageBucket: 'fitfuse-5edc7.firebasestorage.app',
    iosBundleId: 'com.example.fitfuseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsoFTCMtGbtlrABbl9xrh-TkUw2oBd5G8',
    appId: '1:262291939280:ios:6773e8b1375469d27923d5',
    messagingSenderId: '262291939280',
    projectId: 'fitfuse-5edc7',
    storageBucket: 'fitfuse-5edc7.firebasestorage.app',
    iosBundleId: 'com.example.fitfuseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfZpwJMiHp8Ar7mVKd3FgCXUA_s-QzqHw',
    appId: '1:262291939280:web:02e289deb16731907923d5',
    messagingSenderId: '262291939280',
    projectId: 'fitfuse-5edc7',
    authDomain: 'fitfuse-5edc7.firebaseapp.com',
    storageBucket: 'fitfuse-5edc7.firebasestorage.app',
    measurementId: 'G-JNFM76Z96Q',
  );
}
